---
- name: 'authenticate | Authenticate on the Red Hat Portal'
  ansible.builtin.uri:
    url: '{{ _redhat_portal_auth_url }}'
    return_content: true
    method: 'POST'
    body_format: 'form-urlencoded'
    body:
      grant_type: 'refresh_token'
      client_id: 'rhsm-api'
      refresh_token: '{{ _api_token }}'
  register: '__t_auth'
  no_log: true

- name: 'authenticate | Ensure access token has been returned by the API'
  ansible.builtin.assert:
    that:
      - '__t_auth.json is defined'
      - '__t_auth.json is not string'
      - '__t_auth.json is iterable'
      - '__t_auth.json is sequence'
      - '__t_auth.json is mapping'

      - '__t_auth.json.access_token is defined'
      - '__t_auth.json.access_token is string'
      - "__t_auth.json.access_token != ''"
      - '__t_auth.json.access_token != None'
    success_msg: 'The API returned an access token'
    fail_msg: 'The API did not return an access token'
    quiet: '{{ _quiet_assert }}'
  no_log: true

- name: 'authenticate | Set fact: Extract access token'
  ansible.builtin.set_fact:
    __access_token: '{{ __t_auth.json.access_token }}'
...
